version: '3.3'

services:
  grafana:
    image: grafana/grafana
    # volumes:
    #   - ./grafana_config.yml:/etc/grafana/provisioning/dashboards/grafana_config.yml
    ports:
      - 3000:3000
    environment:
      - "GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource"
    