name: Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build covee Docker image
      run: |
        docker build -t covee-image -f covee.Dockerfile .

    - name: Build covee-powerflow Docker image
      run: |
        docker build -t covee-powerflow-image -f covee-powerflow.Dockerfile .

    - name: Run covee Docker container
      run: |
        docker run -d --name covee-container covee-image

    - name: Run covee-powerflow Docker container
      run: |
        docker run -d --name covee-powerflow-container covee-powerflow-image

